version: "3.8"
services:
  php:
    container_name: fony_php
    build: .
    restart: always
    user: "1002:1002"
    volumes:
      - ./:/var/www/fony
    ports:
      - 9000:9000
    depends_on: 
      - db
  db:
    container_name: fony_db
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fony
    ports:
      - '3307:3306'
  nginx:
    container_name: fony_nginx
    restart: always
    image: nginx:stable-alpine
    ports:
      - '8111:80'
    volumes:
      - ./:/var/www/fony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
  adminer:
    container_name: fony_adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: pepa-linha
    ports:
      - 8080:8080